apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cs-rid-c-7da40429-0dc8-4fee-91c5-27c76b78d1ae-plysander-aws-tkg-pl-aws-tks-prov-sp-tkg-wrk1-rbac-sp-read.authorization.k8s.io-ClusterRole-view
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: skandpurohit@gmail.com
